### ISSUE TITLE
On production build Viewer faces an error that Anonymous components are not allowed!

### ISSUE THREAD

**Issue by sectem** [optimajet/formengine#1]
Hi, Recently i started using formengine, but whenever I try to make a production build Formengine viewer gives me error () and nothing gets displayed on screen.
details are attached below

Definer.ts:75 Uncaught Error: Anonymous components are not allowed!
    at define (Definer.ts:75:22)
    at RsBreadcrumb.tsx:39:29
    at index.tsx:34:20
    at index.tsx:34:20

My code is in screenshot

![Screenshot 2023-12-19 at 12 31 16 AM](https://github.com/optimajet/formengine/assets/26120004/cb26f9b3-2652-4057-a8e6-d9ddfa0b9da9)

It perfectly run in dev but in production it gives error

**Comment by sergeythrees** [comment]
> Hi, Recently i started using formengine, but whenever I try to make a production build Formengine viewer gives me error () and nothing gets displayed on screen.

Hi, @sectem 
we have released a version of FormEngine with all the fixes:
https://formengine.io/documentation/release-notes#102
