### ISSUE TITLE
Setting "valued" to an object type in a custom component 

### ISSUE THREAD

**Issue by rainman400** [optimajet/formengine#10]
There is some documentation here about using "valued" to let the component know that the custom component contains a value:
https://formengine.io/documentation/custom-components#custom-component-containing-data

I was wondering how this would work for objects. I know its possible, since the dropdown component from rComponentSuite contains the value in this format, I am just not sure how to translate that into a custom component that would have a similar structure. 

For more info:
 - Just using "value: string.valued.default('')" within the props of define() causes it to throw an error "cannot convert [Object object] from object to string
 - i can override the onChange and propagate the value of event.target.value into the custom component code itself, but the json on the formBuilder still shows an empty string.

**Comment by optimajet** [comment]
@rainman400 thanks for reporting this, we will look into supporting objects as component values.

BTW, by using the `value: string.valued.default('')` operator, you are "telling" FormEngine that the default value is a string.

**Comment by cherepanov** [comment]
@rainman400

We are working on implementing a plain object as a data type.
Could you share your use case for this feature?
RSuite dropdowns support passing a value as an object with a shallow check for the value.
Although it's not documented well.

[Check this demo](https://codesandbox.io/p/sandbox/dd-nmvgzk?file=%2Fsrc%2FApp.js%3A13%2C11)

**Comment by cherepanov** [comment]
Thank you! We will verify the MUI integration.

Both MUI and RSuite support passing values as either primitives or objects.

However, in RSuite, before version 5.50, setting the value as an object is not functional. This feature will necessitate an RSuite upgrade, so please be prepared.

Out of the box, these libraries are capable of handling primitive values combined with simply shaped options ({ label, value }: { string, string }).

Object values are handled differently in each library. Please check the [demo](https://codesandbox.io/p/sandbox/compare-object-values-handling-5sj4ht?file=%2Fsrc%2FApp.js%3A41%2C14)
 for more details.

**Comment by rainman400** [comment]
This looks great.

How does the integration into formbuilder work for this as a custom component?
