### ISSUE TITLE
Crash when RsContainer doesn't exist "props" in the objet

### ISSUE THREAD

**Issue by AlexandroMunera** [optimajet/formengine#11]
The designer and viewer stop working when in the schema some "container" component does not have the "props",  it seems, this prop must exist even if it is empty.

It would be nice if it worked without "props"

It works:
![image](https://github.com/optimajet/formengine/assets/6957621/0e277732-348a-470a-8753-8bc2d6f83e07)

It doesn't work:
![image](https://github.com/optimajet/formengine/assets/6957621/8a1d6ca2-cd00-4934-970d-a299750d4c10)

**Comment by optimajet** [comment]
@AlexandroMunera Yes, `props` are mandatory now. We will make them optional in one of the releases.

**Comment by Skluks** [comment]
@AlexandroMunera 
I wanted to let you know that the props attribute is now optional. You can find more details in the release notes here: [Form Engine Release Notes](https://formengine.io/documentation/release-notes#170).
