### ISSUE TITLE
Download JSON

### ISSUE THREAD

**Issue by git-Aditya67** [optimajet/formengine#2]
Hello, I'm using the <Formbuilder /> from Library @react-form-builder/designer in CRA. is there any way to create or get JSON of That created FORM without Manually Download or Copy From Edit JSON in Front-end because i wanna show the view of That JSON.

**Comment by optimajet** [comment]
Hello @git-Aditya67. We will add functionality to retrieve JSON form in one of the upcoming releases.

**Comment by sergeythrees** [comment]
> Hello, I'm using the from Library @react-form-builder/designer in CRA. is there any way to create or get JSON of That created FORM without Manually Download or Copy From Edit JSON in Front-end because i wanna show the view of That JSON.

Hi @git-Aditya67,
we have released this fuctionality
https://formengine.io/documentation/forms-json#get-the-forms-json-in-react-component

**Comment by Bom312001** [comment]
Hi @sergeythrees 
I tried following the document you updated. But I got error:
![error](https://github.com/user-attachments/assets/16086220-b340-4315-a9e2-fef5dc8eb705)
Only when I write code and save it will I see the JSON. When I reload the page I get this error.
Can you please check the documents and help me?
