### ISSUE TITLE
Data Payload not structured

### ISSUE THREAD

**Issue by Sarim-Sohail** [optimajet/formengine#25]
I'm unable to parse data properly in these scenarios:

![Screenshot_1](https://github.com/optimajet/formengine/assets/66557538/f5073c6f-b987-46dd-9242-2a40569feb88)
Suppose I have many rows of inputs below column-like headers. The data payload just shows rsInput in series. How can I easily get the data of any specific column, like the first row of inputs within a subsection. Is this possible?

**Comment by optimajet** [comment]
@Sarim-Sohail we are working on a component called "Repeater" - this is the component that will help you work with an array of data.

**Comment by Sarim-Sohail** [comment]
> @Sarim-Sohail we are working on a component called "Repeater" - this is the component that will help you work with an array of data.

Is there any date you can estimate for it's release? This feature and the support for object type, I see them in your roadmap but any idea how long till they're completed?

**Comment by optimajet** [comment]
> Is there any date you can estimate for it's release? This feature and the support for object type, I see them in your roadmap but any idea how long till they're completed?

These functions are among our priorities. But we do not publish implementation dates. We very much hope that it will be soon enough.
