### ISSUE TITLE
Update breaks build when using rollup

### ISSUE THREAD

**Issue by jonathanfalkner** [optimajet/formengine#27]
This bump from 1.3.1 to 1.4.0 has started breaking our builds:
https://github.com/optimajet/formengine/commit/06366a2bc01680da24c4ad9e8ab58d573d2e6abb

Rollup failed to resolve import "rsuite/esm/internals/hooks/useUniqueId.js" from "/builds/[removed for privacy reasons]/node_modules/@react-form-builder/designer/dist/index.js".

Version 1.4.0 of RSuite moved where these internals are located. It is also possible that this should have been "@rsuite/" instead of "rsuite/". Either way, the reference in react-form-builder is incorrect.

**Comment by jonathanfalkner** [comment]
Line 63:
import { useUniqueId as Cr } from "rsuite/esm/internals/hooks/useUniqueId.js";

This is what is breaking.

**Comment by optimajet** [comment]
@jonathanfalkner Thank you for reporting this issue. We will fix this issue.

**Comment by optimajet** [comment]
@jonathanfalkner Please try release 1.5.0 - https://formengine.io/documentation/release-notes#150
