### ISSUE TITLE
Triggered custom download callback function

### ISSUE THREAD

**Issue by deri387** [optimajet/formengine#3]
Hi, can i customize form builder download callback action?example when i downloading json i want to store to my database with hit API

**Comment by sergeythrees** [comment]
@deri387 
> Hi, can i customize form builder download callback action?example when i downloading json i want to store to my database with hit API

https://formengine.io/documentation/form-storage

**Comment by optimajet** [comment]
@deri387 You can customise UI elements, have a look at the documentation here - https://formengine.io/documentation/designer-customization
