### ISSUE TITLE
Error: Download JSON #2

### ISSUE THREAD

**Issue by Bom312001** [optimajet/formengine#32]
Hi Guys
I have commented the error details in the article section of git-Aditya67.
https://github.com/optimajet/formengine/issues/2#issuecomment-2251955391

I tried following the document you updated. But I got error:
![error](https://github.com/user-attachments/assets/16086220-b340-4315-a9e2-fef5dc8eb705)
I do not see the JSON in the console.log(). Then When I reload the page I get this error.
Can you please check the documents and help me?(Please show me the steps so I can log the JSON file in my component without having to click download JSON or View JSON)

**Comment by sergeythrees** [comment]
> I tried following the document you updated. But I got error

Hi, @Bom312001 
Show us what code you use for this

**Comment by Bom312001** [comment]
Hi, @sergeythrees 
![image](https://github.com/user-attachments/assets/8d2a1cb9-1f40-4276-8c9b-d29db4bdafbc)
![image](https://github.com/user-attachments/assets/069913b6-5c38-4639-89f6-f733d23686c3)

I have set up correctly according to the document.
I also followed the document, but I can't see the console.log(formJSON) that the document wrote.

Please check again for me?

**Comment by sergeythrees** [comment]
@Bom312001 

You're right, this is a bug. We will fix it in the coming days and let you know how we will release the bugfix.

**Comment by Bom312001** [comment]
@sergeythrees 
Thank you !!! I hope I will receive an answer from you as soon as possible. Because my project is urgently needed.

**Comment by Bom312001** [comment]
Hi @sergeythrees 
Are you sure this is the answer for me?
I have read your fixed note. I don't think it's relevant to my question.

I tried logging out like the code above. I think it encountered an error in formAsString.
Is that right or not ?
Please check the document again ang fix bug for me?
![image](https://github.com/user-attachments/assets/3624d253-8142-4408-9cac-b34df59531cc)

**Comment by Bom312001** [comment]
Hi @sergeythrees 
Are you sure this is the answer for me?
I have read your fixed note. I don't think it's relevant to my question.

I tried logging out like the code above. I think it encountered an error in formAsString. Is that right or not ?
Please check the document again ang fix bug for me?
![image](https://github.com/user-attachments/assets/3624d253-8142-4408-9cac-b34df59531cc)

**Comment by sergeythrees** [comment]
@Bom312001 
> Hi @sergeythrees Are you sure this is the answer for me? I have read your fixed note. I don't think it's relevant to my question.

https://formengine.io/documentation/release-notes#180
> The IFormBuilder ref does not work.

Fixing this bug is relevant to your question. Upgrade packages to version 1.8.0 to see the changes.

**Comment by Bom312001** [comment]
@sergeythrees 
I understand, I have edited the version.
![image](https://github.com/user-attachments/assets/b8be0c30-9564-442e-a501-3cc292d649fc)
And reuslut: 
![image](https://github.com/user-attachments/assets/d08da15b-0d68-4c82-bc67-48a3859c56b5)
 I still don't see any JSON file output from console.log like I clicked download or clicked viewJSON(</>)
 
 Please check again for me? or Please show me your results, and guide me ?

**Comment by sergeythrees** [comment]
@Bom312001 
>  I still don't see any JSON file output from console.log

What comes out in your console after updating packages?

**Comment by sergeythrees** [comment]
@Bom312001  

You need to remove builderRef.current from the condition:
![image](https://github.com/user-attachments/assets/87793dde-4834-4c8a-84af-7b2a949b8c68)

**Comment by Bom312001** [comment]
@sergeythrees 
That's right.
But I'm seeing it only logs the JSON file the first time it enters the interface.
If I drag more fields in and add attributes, I have to wait a while for the JSON file to log out again.
Is that a feature or a bug?

**Comment by Bom312001** [comment]
Hi @sergeythrees 
I want whenever I add fields and adjust properties, the JSON file can update immediately.
Even if I have created the fields before, after changing the properties again, the JSON file will update again.
Because I'm changing your JSON file, it's only logged out the first time, but after I edit the field properties, the JSON file doesn't update and logs out again.

Can you recheck and update the logic as above?

**Comment by Bom312001** [comment]
Hi @sergeythrees
Are you still supporting me?

**Comment by sergeythrees** [comment]
@Bom312001 

Yes, we have already implemented this functionality and will release it soon.

**Comment by Bom312001** [comment]
@sergeythrees
Oh , I got it, thank you guys !!!

**Comment by sergeythrees** [comment]
@Bom312001
> Yes, we have already implemented this functionality and will release it soon.


Done:
https://formengine.io/documentation/release-notes#190

https://formengine.io/documentation/getting-form-json#using-onformschemachange-callback

**Comment by Bom312001** [comment]
@sergeythrees Thank you very much !!!
I'll test again, if any other problems arise, I'll respond to you !

**Comment by Bom312001** [comment]
Hi @sergeythrees! Sorry for bothering you
I discovered another error.
If I get the available fields from the API.
So after adding new fields, I am seeing duplicate keys.
This was difficult when I sent it to BE.
I example input field:
![image](https://github.com/user-attachments/assets/f1ef9839-0e15-4385-ae4a-55ab7cb8786f)
![image](https://github.com/user-attachments/assets/c7bf4a22-d8ce-4bb5-8758-4d8a3ebba5f3)

Can you help me fix this key?

**Comment by optimajet** [comment]
> So after adding new fields, I am seeing duplicate keys.

They are different: `input1` and `Input1` - in the new version of FormEngine the keys are generated as valid JavaScript identifiers. https://formengine.io/documentation/release-notes#190

**Comment by Bom312001** [comment]
Oh thank you @sergeythrees! I realized the problem.
Can you send me a private message to see the code you use to handle duplicate keys for me?

**Comment by sergeythrees** [comment]
@Bom312001 
> Oh!!! thank you, @sergeythrees! I realized the problem.
> 
> Can you send me a private message to see the code you use to handle duplicate keys for me?


```ts
/**
 * Returns true if the component key is unique across the entire component tree. **Internal use only.**
 * @param value the component key.
 * @param store the form viewer settings.
 * @returns true if the component key is unique across the entire component tree.
 */
export const isUniqueKey: RuleValidator<string> = (value, store) =>
  1 === store.reduceScreen((acc, cd) => cd.key === value ? acc + 1 : acc, 0)
```

**Comment by sergeythrees** [comment]
> @sergeythrees  thank you thank you guys,
> 
> But it seems too brief ^-^!
> 
> I want to reference that code to use as a common function for my application
> 
> For example, this is a JSON file and can you give me a common function?
> 
> const arr = [
> 
>   { key: "input1", value: 'aaa' },
> 
>   { key: "input2", value: "bbb" },
> 
>   { key: "input3", value: "ccc" },
> 
>   { key: "input4", value: "ddd" },
> 
>   { key: "input1", value: "eee" },
> 
>   { key: "input2", value: "ggg" }
> 
> ];

@Bom312001 
Please open a new discussion with this question, and also describe there why you need external key verification and how you plan to use it, with real examples.
