### ISSUE TITLE
I need more description API componet for filed timer 

### ISSUE THREAD

**Issue by Bom312001** [optimajet/formengine#38]
I see  APIs for describing a component:
![image](https://github.com/user-attachments/assets/d96d643b-4a43-4efd-9449-feb2c4a90a79)
Can you add api component description for time field ?

![image](https://github.com/user-attachments/assets/af6919b6-e73b-410e-9404-efad466be161)

I'm setting defaultValue = string.
But I'm not sure the user can enter the hh:mm:ss structure correctly.
So can you create an additional api component for time to choose from?

Thank you!!!

**Comment by Bom312001** [comment]
@optimajet
Thank you very much !!! Have a good day

**Comment by sergeythrees** [comment]
Hi, @Bom312001 
we are glad to inform you that we have released a Time picker component and also time annotation for editing properties with the time type:
https://formengine.io/documentation/release-notes#1110

**Comment by sergeythrees** [comment]
Hi, @Bom312001 
we are glad to inform you that we have released a Time picker component and also time annotation for editing properties with the time type:
https://formengine.io/documentation/release-notes#1110
