### ISSUE TITLE
Triggering getForm and hiding toolbar items 

### ISSUE THREAD

**Issue by rainman400** [optimajet/formengine#4]
I was wondering if there is functionality for triggering getForm in the FormBuilder component. For example, I want to update the component with form data based on external (to the component) searches. I want to ideally use my ui and api for this. But, once I have the data, I want to feed it to the component and have it render properly. The data is something that I get from the builderRef so it should ideally just plug and play, but I do not see a way to trigger this right now. 

Also, I was wondering if there is a way to hide the toolbar items, incase we don't need it. For example, disabling the "edit JSON" or "theme" buttons. (This can be done using css hacking, which is what I will go with in case the functionality isn't available yet haha)

**Comment by sergeythrees** [comment]
Hi, @rainman400 
>I was wondering if there is functionality for triggering getForm in the FormBuilder component. For example, I want to update the component with form data based on external (to the component) searches. I want to ideally use my ui and api for this. But, once I have the data, I want to feed it to the component and have it render properly. The data is something that I get from the builderRef so it should ideally just plug and play, but I do not see a way to trigger this right now.

We didn't quite understand what you want. Can you please explain in more detail or show me with an example of the code how it should look?

> Also, I was wondering if there is a way to hide the toolbar items, 
We will add this feature in the next release. Thereafter уou can hide specific parts of the interface using CSS selectors. As example:
```css
.FormBuilder .Property > .CodeButton {
   display: none;
}
```

**Comment by rainman400** [comment]
Let me see if i can pseudo-code something out really quickly: 

`
const [schema,setSchema] = useState<string>('')
const getFromApi = (async () => {
const apiSchema = await OnlineController.getSchema()
setSchema(apiSchema);
})
const getSchemaForBuilder = (() => {
return schema || '' 
})
<FormBuilder
getForm={getSchemaForBuilder}
...other props
/>
`

In this scenario, I want the formBuilder getForm to get triggered everytime 'getFromApi' is called, since it updates the schema variable. I am unsure of how to trigger that though.

For the moment, I have a workaround where I set a 'key' for the FormBuilder and remount it everytime I want to update the schema variable. It's not the worst solution, but maybe there is a better way?

**Comment by sergeythrees** [comment]
There are several ways you can do this. In the code that you have shown, it is enough to add a useCallback:
```typescript
  const [schema,setSchema] = useState<string>('')
  const getSchemaForBuilder = useCallback((formName?: string) => schema, [schema])
  const getFromApi = (async () => {   const apiSchema = await OnlineController.getSchema()   setSchema(apiSchema);   }) 
  return <FormBuilder   getForm={getSchemaForBuilder}   ...other props   />  
```

You can also update the schema directly through builderRef:
```typescript
builderRef.current.parseForm(schema)
```
 or through viewerRef. 
```typescript
viewerRef.current.loadForm(getSchemaForBuilder, name)
```
This is not a documented API yet, we will add documentation soon.
![image](https://github.com/optimajet/formengine/assets/22077517/3c4bc45e-8002-4c43-8998-3759dcdbfeff)
![image](https://github.com/optimajet/formengine/assets/22077517/9ec75e9e-12c9-4573-8e25-7fdb17ae9eea)

**Comment by sergeythrees** [comment]
@rainman400 
There are several ways you can do this. In the code that you have shown, it is enough to add a useCallback:
```typescript
  const [schema,setSchema] = useState<string>('')
  const getSchemaForBuilder = useCallback((formName?: string) => schema, [schema])
  const getFromApi = (async () => {   const apiSchema = await OnlineController.getSchema()   setSchema(apiSchema);   }) 
  return <FormBuilder   getForm={getSchemaForBuilder}   ...other props   />  
```

You can also update the schema directly through builderRef:
```typescript
builderRef.current.parseForm(schema)
```
 or through viewerRef. 
```typescript
viewerRef.current.loadForm(getSchemaForBuilder, name)
```
This is not a documented API yet, we will add documentation soon.
![image](https://github.com/optimajet/formengine/assets/22077517/3c4bc45e-8002-4c43-8998-3759dcdbfeff)
![image](https://github.com/optimajet/formengine/assets/22077517/9ec75e9e-12c9-4573-8e25-7fdb17ae9eea)

**Comment by rainman400** [comment]
Awesome thanks!
