### ISSUE TITLE
dynamic number of slots as node for custom component props

### ISSUE THREAD

**Issue by amirht222** [optimajet/formengine#42]
I'm defining some custom components and I want to have something like a dynamic grid which acts as a parent for other inputs and buttons. how can I set dynamic number of slots and children using props method for example? can I have array of "node" props?
(for example in the Main tab I want a "cols" prop that can change the number of slots and plus signs so I can drop any number of items I want in that grid container)

**Comment by optimajet** [comment]
Right now, `node` is just a description of a property of a component that is a `ReactNode`. If the property is not defined in designer mode - DropZone will be drawn on this place. You can drag multiple components (array) into the DropZone.

We are working on the possibility of adding components like Grid and Repeater.

**Comment by matious89pl** [comment]
@optimajet do you have any timeline regarding Repeater? Your formbuilder product has that, and it would amazing to gave that in formengine.io.

**Comment by optimajet** [comment]
@matious89pl We are working on it. As soon as the component is ready, we will publish it immediately.
