### ISSUE TITLE
Drag and drop bugs and issues

### ISSUE THREAD

**Issue by davidbrinton** [optimajet/formengine#44]
I don't know if this has been reported or if the team is aware of it, but this drag and drop bug is really challenging to live with. The drag and drop isn't as good as I would like it generally, but in particular, this has to just be a bug. It is **very** difficult to drag and drop onto the green + rectangular areas. It's a big issue for our users. It appears as though to successfully drag onto the green + rectangles one has to keep their mouse over the top half of the rectangle. These rectangles are not very tall so there is only a range of maybe 15 pixels that is a valid drop target. What makes this more difficult is the rectangular area moves as you try to hover over it because the styling causes its size to change.

Here is a view of it in action. Is this something that is planned to be fixed soon? We just released our first beta using form engine and I'm worried about general user adoption with this and some of the other drag and drop issues the library has.

![drag and drop](https://github.com/user-attachments/assets/2701de99-62b9-4439-8470-284afaf3c63b)

**Comment by sergeythrees** [comment]
Hi, @davidbrinton 

Thank you for reporting the bug, we will fix it soon and let you know.

**Comment by davidbrinton** [comment]
It looks like this has been categorized so that it can be worked on but I'm not sure if that's what I'm seeing. How can I tell when this has started to be fixed and which version the fix makes it into?

**Comment by sergeythrees** [comment]
Hi, @davidbrinton 
the fix will be released within about two weeks.

**Comment by sergeythrees** [comment]
Hi, @davidbrinton 
we have released a version where we have fixed and improved the Drag and drop behavior: 
https://formengine.io/documentation/release-notes#1130
