### ISSUE TITLE
Support for Table components

### ISSUE THREAD

**Issue by danhnguyeen** [optimajet/formengine#48]
Hi there,

Do you have any plans for Table components? I tried implementing it with a custom component as bellow, but it still didn’t work as expected.

<img width="1258" alt="image" src="https://github.com/user-attachments/assets/e8015817-b6d4-4d66-bda4-e82952ed3c37">

```
import React from 'react';
import { define, number, boolean, node } from '@react-form-builder/core';

export const customTable = define(
  ({
    rows,
    columns,
    hasBorder,
    cellPadding,
    ...props
  }: {
    rows: number;
    columns: number;
    hasBorder: boolean;
    cellPadding: number;
    [key: string]: React.ReactNode;
  }) => {
    const tableStyle = {
      width: '100%',
      borderCollapse: 'collapse' as const,
      border: hasBorder ? '1px solid #ddd' : 'none',
    };

    const cellStyle = {
      border: hasBorder ? '1px solid #ddd' : 'none',
      padding: `${cellPadding}px`,
    };

    return (
      <table style={tableStyle} {...props}>
        <tbody>
          {Array.from({ length: rows }).map((_, rowIndex) => (
            <tr key={rowIndex}>
              {Array.from({ length: columns }).map((_, colIndex) => (
                <td key={colIndex} style={cellStyle}>
                  {props[`cell${rowIndex}${colIndex}`]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
  },
  'CustomTable'
)
  .name('Custom Table')
  .props({
    rows: number.named('Number of Rows').default(3),
    columns: number.named('Number of Columns').default(3),
    hasBorder: boolean.named('Show Borders').default(true),
    cellPadding: number.named('Cell Padding').default(8),
    ...Object.fromEntries(
      Array.from({ length: 3 }).flatMap((_, rowIndex) =>
        Array.from({ length: 3 }).map((_, colIndex) => [
          `cell${rowIndex}${colIndex}`,
          node.named(`Cell ${rowIndex},${colIndex}`),
        ])
      )
    ),
  });
```
The issue in my code is that the number of `cell${rowIndex}${colIndex}` elements is fixed. I’m not sure how to dynamically render nodes based on flexible column/row inputs.

I’m considering allowing users to input the number of columns and rows before rendering the table. However, I haven’t been able to make it work yet
<img width="668" alt="image" src="https://github.com/user-attachments/assets/407dcb64-08bb-49d3-8874-4e4c0bbf23ac">

**Comment by optimajet** [comment]
Hi @danhnguyeen,

Do you want something like an editable table or just a component to display data in a table?

**Comment by danhnguyeen** [comment]
> Hi @danhnguyeen,
> 
> Do you want something like an editable table or just a component to display data in a table?

Hi @optimajet,  
Thanks for your reply. For now, I just need a simple table that allows users to define the number of columns and rows. Each table cell should be a node so users can drag and drop any existing components into it.
Is it possible?
Thank you

**Comment by optimajet** [comment]
Basically, we have something similar to what you need to create such a component. If you look at the [Wizard](https://formengine.io/documentation/components-library/structure-components/wizard) component, you will see that there is a labels property inside the Wizard component. When new items are added, new steps are added to the Wizard. Each step is a separate child component that has a `node` inside it for adding components.

And you can dynamically change the number of rows and columns based on changing the component properties.

There are some important points:
 - For now there are no restrictions for drag'n'drop, i.e. you can drag and drop added components without restrictions.
- You will need to write logic for synchronising the properties of the table component and child components.
<img width="288" alt="image" src="https://github.com/user-attachments/assets/9716f0f8-475f-4a3d-84b1-b3f37a103866">

If you want to try this approach - we can share the code of the Wizard component.

We also have plans to add a similar component based on the [Repeater](https://formengine.io/documentation/components-library/structure-components/repeater) component. Only the number of rows in the table will be adjusted dynamically based on the Repeater component data.

**Comment by danhnguyeen** [comment]
Hi @optimajet,
Yes, the [Wizard](https://formengine.io/documentation/components-library/structure-components/wizard) component seems quite similar to the concept of my Table component. 
Since my Table has fixed data, I may not need the [Repeater](https://formengine.io/documentation/components-library/structure-components/repeater) component.
If possible, could you please share the code for the Wizard component? That would be really helpful.
Thank you

**Comment by danhnguyeen** [comment]
@optimajet Thank you. I will take a look at it
