### ISSUE TITLE
How to extend (modify) rSuiteComponents

### ISSUE THREAD

**Issue by pashaie** [optimajet/formengine#50]
how to add (modify) props or even better clone predefined component?
```typescript
  const dropdown = rSuiteComponents.find(x => x.data.name === 'Dropdown');
  if (!dropdown) return <></>

  dropdown.props({ query_view: oneOf('1', '2'), })
```

above code replaces all previous props with only `query_view`, but we need to only append

**Comment by pashaie** [comment]
```typescript
  const dropdown = rSuiteComponents.find(x => x.data.name === 'Dropdown');
  if (!dropdown) return <></>

  if (dropdown.data.properties)
    dropdown.data.properties['query_view'] = oneOf('1', '2');
```
did the job :)

**Comment by pashaie** [comment]
renaming dropdown with ` dropdown.data.name = "MySelect"` or `dropdown.name('MySelect')` crashes app without logging any error message!

**Comment by optimajet** [comment]
@pashaie 

Can you provide us with sample code to reproduce the error?
