### ISSUE TITLE
Issue Report: Updating Component Keys in Formengine React Library

### ISSUE THREAD

**Issue by seeranjeeviramavel** [optimajet/formengine#6]
**Issue:**
 I'm encountering an issue with the Formengine library in React, specifically related to key changes not reflecting in the calculable value. When I change the key of any component in the form output, it works as expected. However, in the calculable value, which contains 'Test form data', it does not change, and a warning is displayed stating "Has not returned value", despite the functionality working correctly.

**Another Suggestion:**
I suggest that when a component is dragged and dropped, the key should be set as "textbox" without any additional characters like spaces or numbers. This is because the space between "textbox" and "1" is not a valid key in JavaScript. Therefore, my idea is to ensure that when a component is dragged and dropped, it should be named consistently as "textbox". If another textbox is added to the canvas, then the subsequent components can be named as "textbox1" or "textbox 1".

I appreciate your attention to this matter and look forward to a resolution that enhances the usability and reliability of the Formengine library.

Thank you for your time and assistance.

**Comment by sergeythrees** [comment]
Hi, @seeranjeeviramavel 

Thank you for reporting these nuances. We will solve this problem for you when we release a fix.
