### ISSUE TITLE
Formbuilder clashes in i18n library/ dropdowns seem to render elsewhere

### ISSUE THREAD

**Issue by rainman400** [optimajet/formengine#7]
https://github.com/optimajet/formengine/assets/19976804/b69de9cd-06e0-416d-9c91-2e0767a2784b

Attaching the above noticed issues when integrating the formbuilder into the app.

1. Looks like it clashes with i18n libraries that are already existing within the app. I was able to fix it for the app itself, but creating an instance of i18n, but this doesn't seem to help Formbuilder itself. Maybe something to look at or there is another way around it?

2. The dropdowns seem to spaz out, as you can see in the video, it appears elsewhere on screen. They are still selectable using arrow keys but the user has no idea what is being selected. 

Let me know if there is more info required, would be happy to provide it!

**Comment by sergeythrees** [comment]
Hi, @rainman400 
a very interesting and unusual bug. Could you please send your project code? Then we can reproduce the bug and figure out what's going on.

**Comment by rainman400** [comment]
Sure thing, currently workng on pruning it a bit, is there somewhere I can send it that is not a super public forum? haha.

**Comment by rainman400** [comment]
added you to a repo where I uploaded the project files :)

**Comment by sergeythrees** [comment]
Hi, @rainman400 
we looked and realized that the problem is related to the build using react-scripts or create-react-app. We have created a task and we will solve it soon.

**Comment by sergeythrees** [comment]
Hi, @rainman400 
We have already released a fix and it is available in the current version.
https://formengine.io/documentation/release-notes
