### ISSUE TITLE
Forms Tab is Not available?

### ISSUE THREAD

**Issue by seeranjeeviramavel** [optimajet/formengine#9]
When comparing the online demo of the FormEngine library ([link to demo](https://demo.formengine.io/)) with my local  implementation using this repository,

 I noticed a slight difference in the builder interface.
Specifically, the online demo features a "Forms" tab in the builder, whereas the local implementation does not include this tab.
Can I know why the feature is not included in this?

**Form Engine Demo**
<img width="960" alt="Demo Formengine" src="https://github.com/optimajet/formengine/assets/114507428/3315a43c-bf6b-4f33-83d1-9562d1808502">

**Form Engine Local:**
![Form Engine Local](https://github.com/optimajet/formengine/assets/114507428/923a1ada-9b5a-44af-ad47-d24520aa1815)

**Comment by optimajet** [comment]
Hi @seeranjeeviramavel,

You just need to connect your own form storage, as in this part of the documentation - https://formengine.io/documentation/form-storage. And this tab will appear.
